[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
# Release
version = "0.1.1"
publish = true
license = "MIT"

# Rust
edition = "2024"
rust-version = "1.92"

# Metadata
authors = ["Nvisy <support@nvisy.com>"]
repository = "https://github.com/nvisycom/sdk-rs"
homepage = "https://nvisy.com"
documentation = "https://docs.nvisy.com"
keywords = ["nvisy", "redaction", "pii", "sdk", "async"]
categories = ["api-bindings", "asynchronous"]

[workspace.dependencies]
# HTTP
reqwest = { version = "0.13", default-features = false, features = ["json", "multipart"] }
reqwest-middleware = { version = "0.5", features = ["json", "multipart", "query"] }
reqwest-retry = { version = "0.9", features = [] }
url = { version = "2.5", features = [] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = [] }

# Primitives
jiff = { version = "0.2", features = ["serde"] }
uuid = { version = "1.22", features = ["serde", "v4"] }

# Error handling
thiserror = { version = "2.0", features = [] }

# Derive macros and utilities
derive_builder = { version = "0.20", features = [] }
base64 = { version = "0.22", features = [] }
futures-core = { version = "0.3", features = [] }
schemars = { version = "1.2", features = ["uuid1"] }

# Observability
tracing = { version = "0.1", features = [] }
reqwest-tracing = { version = "0.7", features = [] }

# Dev
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
