//! File-related data models.

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Represents an uploaded file.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct File {
    /// Unique file identifier.
    pub file_id: Uuid,
    /// Display name.
    pub display_name: String,
    /// File size in bytes.
    pub file_size: i64,
    /// Processing status.
    pub status: ProcessingStatus,
    /// How the file was created.
    pub source: FileSource,
    /// Classification tags.
    pub tags: Vec<String>,
    /// Processing priority (1-10).
    pub processing_priority: i32,
    /// Knowledge extraction settings.
    pub file_knowledge: FileKnowledge,
    /// Account ID of the uploader.
    pub uploaded_by: Uuid,
    /// Creation timestamp.
    pub created_at: String,
    /// Last update timestamp.
    pub updated_at: String,
}

/// Processing status of a file.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProcessingStatus {
    /// File is waiting to be processed.
    Pending,
    /// File is currently being processed.
    Processing,
    /// File has been processed successfully.
    Completed,
    /// Processing failed.
    Failed,
}

/// Source of the file.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FileSource {
    /// File was uploaded directly.
    Uploaded,
    /// File was imported from an external source.
    Imported,
    /// File was generated by the system.
    Generated,
}

/// Knowledge extraction settings for a file.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FileKnowledge {
    /// Whether OCR is enabled.
    #[serde(default)]
    pub ocr_enabled: bool,
    /// Whether embeddings should be generated.
    #[serde(default)]
    pub embeddings_enabled: bool,
    /// Content segmentation strategy.
    #[serde(default)]
    pub segmentation: ContentSegmentation,
}

impl Default for FileKnowledge {
    fn default() -> Self {
        Self {
            ocr_enabled: true,
            embeddings_enabled: true,
            segmentation: ContentSegmentation::default(),
        }
    }
}

/// Content segmentation strategy.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ContentSegmentation {
    /// Page-based segmentation.
    #[default]
    Page,
    /// Semantic-based segmentation.
    Semantic,
    /// Fixed-size chunks.
    Chunk,
}

/// Supported file formats.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum FileFormat {
    /// PDF documents.
    Pdf,
    /// Microsoft Word documents.
    Docx,
    /// Microsoft Excel spreadsheets.
    Xlsx,
    /// Microsoft PowerPoint presentations.
    Pptx,
    /// Plain text files.
    Txt,
    /// Markdown files.
    Md,
    /// HTML files.
    Html,
    /// Image files.
    Image,
}

/// Request body for updating a file.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateFile {
    /// New display name.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// New tags.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// New processing priority (1-10).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub processing_priority: Option<i32>,
}

/// Paginated list of files.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FilesPage {
    /// List of files.
    pub items: Vec<File>,
    /// Cursor for the next page.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    /// Whether there are more results.
    pub has_more: bool,
}

/// Request for batch file deletion.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeleteFiles {
    /// List of file IDs to delete.
    pub file_ids: Vec<Uuid>,
}

/// Archive format for batch downloads.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ArchiveFormat {
    /// ZIP archive format.
    #[default]
    Zip,
    /// TAR.GZ archive format.
    #[serde(rename = "tar.gz")]
    TarGz,
}

/// Request for batch file download.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DownloadFiles {
    /// List of file IDs to download. If empty, downloads all files.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub file_ids: Vec<Uuid>,
    /// Archive format.
    #[serde(default)]
    pub format: ArchiveFormat,
}
